# Generated by Django 5.2.17 on 2026-10-05 01:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_representative', models.BooleanField(default=False, verbose_name='Pode ser representante?')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('invitation_link', models.URLField(blank=True, null=True, verbose_name='Link de convite')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
