# Generated by Django 5.2.17 on 2026-10-05 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0001_initial'),
        ('voxum_base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userguest',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='voxum_base.entity', verbose_name='Entidade'),
        ),
        migrations.AddField(
            model_name='userguest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
