# Generated by Django 4.2.30 on 2026-10-03 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditors', '0001_initial'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True, verbose_name='Presente')),
                ('signed_in_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Entrada')),
                ('signed_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Saída')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='creditors.creditor')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='meetings.meeting')),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='creditors.representative')),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
                'unique_together': {('meeting', 'creditor')},
            },
        ),
    ]
