# Generated by Django 5.2.17 on 2026-10-05 01:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrival_date', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora de chegada')),
                ('departure_date', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora de saída')),
                ('departure_reason', models.TextField(blank=True, null=True, verbose_name='Motivo da saída')),
                ('is_present', models.BooleanField(default=False, verbose_name='Está presente')),
                ('is_accredited', models.BooleanField(default=False, verbose_name='O Credor está está credenciado')),
                ('accredited_date', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora do credenciamento')),
                ('accredited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('creditor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='creditor.creditor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PresenceRepresentative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrival_date', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora de chegada')),
                ('departure_date', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora de saída')),
                ('departure_reason', models.TextField(blank=True, null=True, verbose_name='Motivo da saída')),
                ('is_present', models.BooleanField(default=False, verbose_name='Está presente')),
                ('representative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='creditor.representative')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
