# Generated by Django 5.2.17 on 2026-10-05 01:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('meetings', '0001_initial'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='converter/pdf/%Y/%m/%d/')),
                ('task_id', models.UUIDField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('R', 'Lista de Representantes'), ('P', 'Lista de Representantes Presentes'), ('C', 'Lista de Credores'), ('E', 'Lista de Credores Presentes')], max_length=1)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
                ('task_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_results.taskresult')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportVoting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='converter/pdf/%Y/%m/%d/')),
                ('task_id', models.UUIDField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('R', 'Relatório de Votação Detalhado'), ('V', 'Votantes Presentes'), ('D', 'Relatório de Votação Detalhado com ressalvas'), ('P', 'Votantes Presentes com ressalvas')], max_length=1)),
                ('task_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_results.taskresult')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.voting')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
