# Generated by Django 5.2.17 on 2026-10-05 01:52

import apps.creditor.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_person', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica'), ('O', 'Outro')], max_length=1)),
                ('credit_value', models.FloatField()),
                ('converted_value', models.FloatField(default=0)),
                ('exchange_tax', models.FloatField(default=0)),
                ('contested_value', models.FloatField(default=0)),
                ('online', models.BooleanField(default=False, verbose_name='Está online?')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Priority')),
                ('code', models.BigIntegerField(default=apps.creditor.models.get_new_creditor_code, editable=False, unique=True)),
                ('meeting_invited', models.BooleanField(default=False)),
                ('doc_ok', models.BooleanField(default=False, verbose_name='Documentação ok?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Soft delete')),
            ],
            options={
                'ordering': ('guest__user__first_name', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveIntegerField(verbose_name='Priority')),
                ('online', models.BooleanField(default=False, verbose_name='Está online?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Soft delete')),
            ],
            options={
                'ordering': ('representative__guest__user__first_name', 'created_at'),
            },
        ),
    ]
