# Generated by Django 5.2.17 on 2026-10-05 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditor', '0001_initial'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meetings.classe'),
        ),
    ]
