# Generated by Django 5.2.17 on 2026-10-05 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditor', '0002_initial'),
        ('guest', '0001_initial'),
        ('meetings', '0001_initial'),
        ('recovering', '0001_initial'),
        ('voxum_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='voxum_base.coin'),
        ),
        migrations.AddField(
            model_name='creditor',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.userguest'),
        ),
        migrations.AddField(
            model_name='creditor',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='creditor',
            name='recovering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recovering.recovering'),
        ),
        migrations.AddField(
            model_name='representative',
            name='creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditor.creditor'),
        ),
        migrations.AddField(
            model_name='representative',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.representativemeeting'),
        ),
        migrations.AlterUniqueTogether(
            name='creditor',
            unique_together={('meeting', 'guest', 'classe')},
        ),
        migrations.AlterUniqueTogether(
            name='representative',
            unique_together={('representative', 'creditor')},
        ),
    ]
