# Generated by Django 4.2.30 on 2026-10-03 21:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome / Razão Social')),
                ('cpf_cnpj', models.CharField(max_length=18, verbose_name='CPF/CNPJ')),
                ('creditor_class', models.CharField(choices=[('LABOR', 'Classe I - Trabalhista'), ('SECURED', 'Classe II - Garantia Real'), ('UNSECURED', 'Classe III - Quirogratário'), ('MICRO', 'Classe IV - ME / EPP')], max_length=20, verbose_name='Classe')),
                ('credit_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor do Crédito')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('doc_ok', models.BooleanField(default=False, verbose_name='Documentação Aprovada')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credor',
                'verbose_name_plural': 'Credores',
            },
        ),
        migrations.CreateModel(
            name='RecoveringCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome / Razão Social')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa Recuperanda',
                'verbose_name_plural': 'Empresas Recuperandas',
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Representante')),
                ('cpf_cnpj', models.CharField(max_length=18, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('is_power_of_attorney_ok', models.BooleanField(default=False, verbose_name='Procuração Válida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='creditors.creditor')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
            },
        ),
        migrations.AddField(
            model_name='creditor',
            name='recovering_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditors', to='creditors.recoveringcompany'),
        ),
        migrations.AddIndex(
            model_name='creditor',
            index=models.Index(fields=['cpf_cnpj'], name='creditors_c_cpf_cnp_0e4cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='creditor',
            index=models.Index(fields=['creditor_class'], name='creditors_c_credito_a274b2_idx'),
        ),
    ]
