# Generated by Django 5.2.17 on 2026-10-05 01:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count_voters', models.PositiveIntegerField(default=0)),
                ('percentage_voters', models.FloatField(default=0)),
                ('count_qualified_creditors', models.IntegerField(default=0)),
                ('total_voters_credit_value', models.FloatField(default=0)),
                ('total_percentage_voters', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClasseResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count_voters', models.PositiveIntegerField(default=0)),
                ('count_qualified_creditors', models.PositiveIntegerField(default=0)),
                ('count_accredited_creditors', models.PositiveIntegerField(default=0)),
                ('count_remaining', models.PositiveIntegerField(default=0)),
                ('percentage_voters', models.FloatField(default=0)),
                ('percentage_remaining', models.FloatField(default=0)),
                ('total_credit_value', models.FloatField(default=0)),
                ('total_accredited_credit_value', models.FloatField(default=0)),
                ('total_voters_credit_value', models.FloatField(default=0)),
                ('total_remaining', models.FloatField(default=0)),
                ('total_percentage_voters', models.FloatField(default=0)),
                ('total_percentage_remaining', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
