# Generated by Django 5.2.17 on 2026-10-05 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('big_number', '0001_initial'),
        ('meetings', '0001_initial'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceresult',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.choice'),
        ),
        migrations.AddField(
            model_name='classeresult',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meetings.classe'),
        ),
        migrations.AddField(
            model_name='classeresult',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.voting'),
        ),
        migrations.AddField(
            model_name='choiceresult',
            name='classe_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='big_number.classeresult'),
        ),
    ]
