# Generated by Django 5.2.17 on 2026-10-05 01:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditor', '0001_initial'),
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('S', 'Assunto'), ('C', 'Escolha')], max_length=1)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de fim')),
                ('status', models.CharField(choices=[('A', 'Agendada'), ('I', 'Iniciada'), ('E', 'Encerrada'), ('D', 'Atrasada'), ('R', 'Reagendada')], db_index=True, default='A', max_length=1, verbose_name='Status')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
            ],
            options={
                'ordering': ('-start_date', '-created_at', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(db_index=True, max_length=100, verbose_name='Value')),
                ('order', models.PositiveIntegerField(default=3, editable=False)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meetings.classe')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.voting')),
            ],
            options={
                'ordering': ('order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='VotingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_reservations', models.BooleanField(default=False, verbose_name='Há ressalvas?')),
                ('type', models.CharField(choices=[('N', 'Sem votante'), ('D', 'Voto por um usuário do sistema'), ('C', 'Voto pelo Credor'), ('R', 'Voto pelo Representante')], default='N', max_length=1, verbose_name='Tipo de Usuário que votou')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditor.creditor')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.choice')),
                ('voted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('value', 'voting', 'classe'), name='unique_value_choice', violation_error_message='Já existe um registro com o mesmo valor da opção para essa votação.'),
        ),
    ]
