# Generated by Django 4.2.30 on 2026-10-03 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditors', '0001_initial'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título / Objeto da Votação')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição / Detalhes')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Não Iniciada'), ('OPEN', 'Em Andamento'), ('CLOSED', 'Encerrada'), ('CANCELLED', 'Cancelada')], default='NOT_STARTED', max_length=20, verbose_name='Status')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Abertura')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Encerramento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Votação',
                'verbose_name_plural': 'Votações',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('YES', 'Sim / A favor'), ('NO', 'Não / Contra'), ('ABSTAIN', 'Abstenção')], max_length=10, verbose_name='Opção de Voto')),
                ('creditor_class', models.CharField(choices=[('LABOR', 'Classe I - Trabalhista'), ('SECURED', 'Classe II - Garantia Real'), ('UNSECURED', 'Classe III - Quirogratário'), ('MICRO', 'Classe IV - ME / EPP')], max_length=20, verbose_name='Classe no Momento do Voto')),
                ('credit_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Crédito no Momento')),
                ('voted_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora do Voto')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='creditors.creditor')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.poll')),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='creditors.representative')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'unique_together': {('poll', 'creditor')},
            },
        ),
    ]
