# Generated by Django 5.2.17 on 2026-10-05 01:52

import apps.meetings.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('guest', '0001_initial'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='MeetingGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('zoom_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('S', 'Agendada'), ('I', 'Iniciada'), ('P', 'Suspensa'), ('F', 'Encerrada')], default='S', max_length=1)),
                ('status_quorum', models.CharField(choices=[('F', 'Primeira convocação'), ('S', 'Segunda convocação'), ('R', 'Quórum atingido'), ('N', 'Quórum não atingido')], default='F', max_length=1)),
                ('situation', models.CharField(choices=[('R', 'Regular'), ('S', 'Suspensa')], default='R', max_length=1)),
                ('order', models.PositiveIntegerField(default=1)),
                ('installed', models.BooleanField(default=False)),
                ('presence_registration_started_at', models.DateTimeField(blank=True, null=True)),
                ('presence_registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='location.location')),
                ('meeting_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_meetings', to='meetings.meeting')),
                ('meeting_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='meetings.meetinggroup')),
            ],
            options={
                'ordering': ('-start_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='RepresentativeMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.PositiveIntegerField(default=apps.meetings.models.get_new_representative_code, unique=True)),
                ('doc_ok', models.BooleanField(default=False)),
                ('meeting_invited', models.BooleanField(default=False)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_representatives', to='guest.userguest')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representativemeeting_set', to='meetings.meeting')),
            ],
            options={
                'ordering': ('guest__user__first_name', 'created_at'),
                'unique_together': {('meeting', 'guest')},
            },
        ),
        migrations.CreateModel(
            name='UserMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='meeting_roles', to='auth.group')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meetings', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
