# Generated by Django 4.2.30 on 2026-10-03 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título da Assembleia')),
                ('call_type', models.CharField(choices=[('1_CALL', '1ª Convocação'), ('2_CALL', '2ª Convocação'), ('CONTINUATION', 'Continuação')], max_length=20, verbose_name='Convocação')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendada'), ('IN_PROGRESS', 'Em Andamento'), ('PAUSED', 'Suspensa / Pausada'), ('FINISHED', 'Encerrada'), ('CANCELLED', 'Cancelada')], default='SCHEDULED', max_length=20, verbose_name='Status')),
                ('start_date', models.DateTimeField(verbose_name='Data / Hora de Início')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data / Hora do Encerramento')),
                ('meeting_link', models.URLField(blank=True, null=True, verbose_name='Link da Transmissão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recovering_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='creditors.recoveringcompany')),
            ],
            options={
                'verbose_name': 'Assembleia',
                'verbose_name_plural': 'Assembleias',
            },
        ),
    ]
